version: '3'
services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
